### ISSUE TITLE
Makefile无法使用

### ISSUE THREAD

**Issue by tianzixiaotanzhong** [runmec/stm32f10x_makefile_template#1]
### 你好，我在windows平台，使用gcc-arm-none-eabi-5_4编译器，git clone后在路径下make，出现了以下错误:
`arm-none-eabi-gcc    -c -o stm32f10x_lib/CMSIS/CM3/DeviceSupport/ST/STM32F10x/startup/gcc_ride7/startup_stm32f10x_md_vl.o stm32f10x_lib/CMSIS/CM3/DeviceSupport/ST/STM32F10x/startup/gcc_ride7/startup_stm32f10x_md_vl.s
arm-none-eabi-gcc    -c -o user/main.o user/main.c
user/main.c:5:23: fatal error: stm32f10x.h: No such file or directory
compilation terminated.
make: *** [<builtin>: user/main.o] Error 1`

**Comment by freelamb** [comment]
for linux or osx is ok
